name: Daily Stock Report

on:
  schedule:
    #run at 02:00 UTC (09:00 AM Thailand Time)
    - cron: '30 6 * * *'
  #allow you to click "Run Now" manually for testing
  workflow_dispatch:

jobs:
  run_tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: pip install yfinance requests supabase

      - name: Run Stock Tracker
        env:
          DISCORD_URL: ${{ secrets.DISCORD_URL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python check_stocks.py

      - name: Run Parcel Tracker
        env:
          DISCORD_URL: ${{ secrets.DISCORD_URL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          TRACK17_KEY: ${{ secrets.TRACK17_KEY }} # Don't forget this new secret!
        run: python check_parcels.py
