name: Daily Report

on:
  schedule:
    #run at 02:00 UTC (14:00 Thailand Time)
    - cron: '30 6 * * *'
  #allow you to click "Run Now" manually for testing
  workflow_dispatch:

jobs:
  run_daily_reports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: pip install yfinance requests supabase

      # Run Stock Report
      - name: Run Stock Tracker
        env:
          STOCK_DISCORD_URL: ${{ secrets.STOCK_DISCORD_URL }} 
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python daily_stock_report.py

      # Run Daily Parcel Summary 
      - name: Run Daily Parcel Summary
        env:
          PARCEL_DISCORD_URL: ${{ secrets.PARCEL_DISCORD_URL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          TRACK17_KEY: ${{ secrets.TRACK17_KEY }}
        run: python daily_parcel_report.py
